import './globals.css';
import {Inter} from 'next/font/google';
import Link from 'next/link';
import LoginBtn from '@/app/LoginBtn';
import {getServerSession} from 'next-auth';
import {authOptions} from '@/pages/api/auth/[...nextauth]';
import LogoutBtn from '@/app/LogoutBtn';
import {cookies} from 'next/headers';
import dynamic from 'next/dynamic';

const inter = Inter({subsets: ['latin']});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({children}) {
    const session = await getServerSession(authOptions);
    const isDarkMode = cookies().get('mode')?.value === 'dark';

    /** * Pure Client Side Rendering
     * https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr */
    const DynamicDarkMode = dynamic(() => import('@/app/DarkMode'), {ssr: false, loading: () => <span> 🎨️</span>});

    return (
        <html lang="en">
            <body className={`${inter.className} ${isDarkMode ? 'dark-mode' : ''}`}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href={'/list'}>List</Link>
                    {!!session ? <LogoutBtn /> : <LoginBtn />}
                    <DynamicDarkMode />
                </div>
                <div>{children}</div>
            </body>
        </html>
    );
}
